# main simualtion configuration file with all the parameters

simulation:
  seed: 32
  duration: 500 # in steps

world:
  size: 100 # 100x100 continuous space
  boundaries: false # no wrap around, how to do this?
  charging_station: [50, 50]

humans:
  human_1:
    num: 1
    initial_wealth: 2000 # IEC
    schedule: false # not implemented yet
    speed: 2 # units/min
    services: 
      - BatteryCharging: { skill: 0.95}
      - LabCleaning: { skill: 0.95 }
      - ItemTransport: { skill: 0.95 }
      - PowerSupply: { skill: 0.95 }
      - SystemUpdate: { skill: 0.95 }
      - FunctionalityTest: { skill: 0.95 }


  human_2:
    num: 1
    initial_wealth: 2000 # IEC
    schedule: false # not implemented yet
    speed: 2 # units/min
    services: 
      - BatteryCharging: { skill: 0.95}
      - LabCleaning: { skill: 0.95 }
      - ItemTransport: { skill: 0.95 }
      - PowerSupply: { skill: 0.95 }
      - SystemUpdate: { skill: 0.95 }
      - FunctionalityTest: { skill: 0.95 }

robots:
  robot_1: 
    num: 1
    initial_wealth: 2000
    initial_battery: 100
    speed: 1.5 # units/min
    random_walk_interval: 5 # change target every k steps
    services: 
      - LabCleaning: { skill: 0.95 }
      - ItemTransport: { skill: 0.95 }
      - SurveillancePatrol: { skill: 0.95 }
      - ComponentRestock: { skill: 0.95 }

  robot_2: 
    num: 1
    initial_wealth: 2000
    initial_battery: 100
    speed: 1.5 # units/min
    random_walk_interval: 5 # change target every k steps
    services: 
      - LabCleaning: { skill: 0.95 }
      - ItemTransport: { skill: 0.95 }
      - SurveillancePatrol: { skill: 0.95 }
      - ComponentRestock: { skill: 0.95 }

battery: # same for all robots
  recharge_rate: 0.167 # units/min maybe out this in minutes?
  drain_rate: 0.2 # units/min
  recharge_trigger: 30 # battery threshold to ask for a recharge
  min_accept_task: 35 # percentage

tasks:
  arrival_rate: 6 # tasks/hour
  proximity_threshold: 0.5 # units to consider at location

assignment_policy: random

pricing_model: fixed

services:
  BatteryCharging:
    category: maintenance
    reward: {median: 120, sigma_g: 0}
    phases:
      waypoints:
        - id: station
          point: { type: charging_station }
          duration: {mean: 10, sd: 0, min: 10} # in steps
          fail: 0.0
      in_order: true
      repeat: 0

  PowerSupply:
    category: maintenance
    reward: {median: 120, sigma_g: 0}
    phases:
      waypoints:
        - id: site
          point: { type: random_in_world }
          duration: {mean: 10, sd: 0, min: 10} # in steps
          fail: 0.0
      in_order: true
      repeat: 0

  ComponentRestock:
    category: maintenance
    reward: {median: 120, sigma_g: 0}
    phases:
      waypoints:
        - id: site
          point: { type: random_in_world }
          duration: {mean: 10, sd: 0, min: 10} # in steps
          fail: 0.0
      in_order: true
      repeat: 0

  SystemUpdate:
    category: maintenance
    performed_by: # agent ids here TODO
    reward: {median: 120, sigma_g: 0}
    phases:
      waypoints:
        - id: site
          point: { type: random_in_world }
          duration: {mean: 10, sd: 0, min: 10} # in steps
          fail: 0.0
      in_order: true
      repeat: 0

  FunctionalityTest:
    category: maintenance
    reward: {median: 120, sigma_g: 0}
    phases:
      waypoints:
        - id: site
          point: { type: random_in_world }
          duration: {mean: 10, sd: 0, min: 10} # in steps
          fail: 0.0
      in_order: true
      repeat: 0
    
  LabCleaning:
    category: cleaning
    reward: {median: 140, sigma_g: 0.35}
    phases:
      waypoints:
        - id: area
          point: { type: random_in_world }
          duration: {mean: 20, sd: 8, min: 6} # in steps
          fail: 0.0
      in_order: true
      repeat: 0
    
  ItemTransport:
    category: transport
    reward: {median: 130, sigma_g: 0.35}
    phases:
      waypoints:
        - id: pickup
          point: { type: random_in_world }
          duration: 10 # in steps
          fail: 0.08 # probability of failure
        - id: dropoff
          point: { type: random_in_world }
          duration: 10
          fail: 0.01
      in_order: true
      repeat: 0
    
  SurveillancePatrol:
    category: security
    reward: {median: 180, sigma_g: 0.35}
    phases:
      waypoints:
        - id: patrol_1
          point: { type: random_in_world }
          duration: {mean: 30, sd: 10, min: 10} # in steps
          fail: 0.0
      in_order: true
      repeat: 0
